[WIP] Add Chass Import Button
uoft-tapp/old-orig-tapp pull request #123
Opened 2017-07-27 22:14 UTC by michellemtchai

2017-07-31 17:35 UTC, gabriellesc commented on app/assets/stylesheets/app.css
> +    padding: 0 !important;
I think it looks a little better with some padding - maybe 5px?

2017-07-31 17:36 UTC, gabriellesc commented on app/assets/stylesheets/app.css
> +    height: 200px;
I think it's a bit easier to read if it's taller - maybe 400px?

2017-07-31 17:38 UTC, gabriellesc commented on app/assets/stylesheets/app.css
> +    width: calc(100% - 27px);
Just wanted to make a note that, if padding is added, this width calculation will change...

2017-07-31 17:41 UTC, gabriellesc commented on app/javascript/app/components/summary.js
> +    Overlay,
`Overlay` doesn't appear to be used anywhere?

2017-07-31 17:42 UTC, freeatnet commented on app/controllers/import_controller.rb
> +    import = promise{ChassImporter.new(params[:chass_json])}
Hmm. Could you explain what happens here?

2017-07-31 17:43 UTC, freeatnet commented on package.json
> +    "gem": "^2.4.2",
What's this for?

2017-07-31 18:13 UTC, gabriellesc requested changes

2017-07-31 18:13 UTC, gabriellesc commented on app/javascript/app/components/summary.js
> +import * as fetch from '../fetch.js';
fetch should *not* be imported here - any fetch functions should be wrapped in appState, and the appState wrapper function should be called from here

2017-07-31 18:13 UTC, gabriellesc commented on app/javascript/app/components/summary.js
> +                if (confirm(message)) this.uploadFile(files[0]);
Missing curly braces, so `prettier` put this on a single line...

2017-07-31 18:13 UTC, gabriellesc commented on app/javascript/app/components/summary.js
> +    loadFile() {
There's no reason to put `loadFile` and `uploadFile` in `Summary` - I think it makes more sense to put them directly into `ImportForm`. I've turned `ImportForm` and `ExportForm` into more than functional classes in #126, where member functions can be attached.

2017-07-31 18:13 UTC, gabriellesc commented on app/javascript/app/fetch.js
> +function showMessage(resp) {
I think we should stick to the alert and notification functionality that we've defined; in this case, I think it makes sense to make this a notification.

2017-07-31 18:13 UTC, gabriellesc commented on app/javascript/app/fetch.js
> +    return postHelper('/import/chass', data, success, failure);
We need to call fetchAll after this completes successfully!

2017-07-31 18:13 UTC, gabriellesc commented on app/javascript/app/components/summary.js
> +                    <button className="info-button" type="button">
I don't think that this icon needs to be wrapped in a button?

2017-07-31 18:13 UTC, gabriellesc commented on app/javascript/app/components/summary.js
> +            >
This is a minor thing but it seems really strange to me - when I run `prettier` on this, it actually puts the closing `>` on the same line as the `}}`. I'm wondering if your `prettier` is configured differently from https://github.com/uoft-tapp/tapp/wiki/JavaScript-JSX-Style ?

2017-08-01 14:44 UTC, michellemtchai commented on app/controllers/import_controller.rb
> +    import = promise{ChassImporter.new(params[:chass_json])}
This waits for the ChassImporter to finish inserting the CHASS JSON to the DB before `importer.done` is called for the Import complete message. Before that no render is done by the controller.

2017-08-01 14:51 UTC, michellemtchai commented on app/javascript/app/components/summary.js
> +            >
It is actually the same setting as what's on the link. I don't know why it's causing this issue.

2017-08-01 15:46 UTC, freeatnet commented on app/controllers/import_controller.rb
> +    import = promise{ChassImporter.new(params[:chass_json])}
Are there any asynchronous operations in ChassImporter? If there is not, maybe we don't need an asynchronous concept of promises here.

2017-08-01 15:48 UTC, michellemtchai commented on app/controllers/import_controller.rb
> +    import = promise{ChassImporter.new(params[:chass_json])}
When I try to do without the promise, the render always finishes before the import is done.

2017-08-01 16:35 UTC, jmzaleski reviewed
worked on my machine!

2017-08-01 17:45 UTC, gabriellesc commented on app/javascript/app/components/summary.js
> +                    <Utilities loadFile={() => this.loadFile()} {...this.props} />
I think this should be removed?

2017-08-01 17:45 UTC, gabriellesc commented on app/javascript/app/components/summary.js
> +            <ImportForm loadFile={props.loadFile} {...props} />
I think this should be removed?

2017-08-01 17:45 UTC, jmzaleski approved these changes

2017-08-01 17:46 UTC, gabriellesc commented on app/javascript/app/components/summary.js
> +    uploadFile(file, func) {
Would it be possible to give `func` a more descriptive name and/or put in a comment describing its purpose?

2017-08-01 17:46 UTC, gabriellesc commented on app/javascript/app/components/summary.js
> +                alert('Error: This is not a CHASS JSON.');
I think we should use the app alert function here?

2017-08-01 17:51 UTC, gabriellesc commented on app/javascript/app/components/summary.js
> +            alert('Error: No file chosen.');
I think we should use the app alert function here?

2017-08-01 17:51 UTC, gabriellesc commented on app/javascript/app/components/summary.js
> +                alert('Error: The file you uploaded is not a JSON.');
I think we should use the app alert function here?

2017-08-02 21:11 UTC, gabriellesc approved these changes

2017-08-02 22:38 UTC, merged