Create CHASS JSON importer
uoft-tapp/old-orig-tapp pull request #29
Opened 2017-06-05 16:49 UTC by michellemtchai

- created importer CHASS JSON 
- imported data to ActiveRecord Models

2017-06-06 14:57 UTC, freeatnet commented on app/services/chass_importer.rb
> +    return @course_data[0]["round_id"]
Let's make sure this isn't nil or inconsistent. Maybe something along the lines of
```
# take round_id from every course_entry; if they are all the same, we'll end up with a single value
round_ids = @course_data.map { |course_entry| course_entry["round_id"] }.uniq
case round_ids.length
when 0
  raise StandardError.new("no round_id found in the file")
when 1
  round_ids.first
else
  raise StandardError.new("too many round_ids found in the file")
end
```

2017-06-06 14:59 UTC, freeatnet commented on app/services/chass_importer.rb
> +          check_duplicate = ["applicant_id = ? and position_id = ? and round_id = ?",
This can be more succinctly expressed as `{applicant_id: applicant_id, position_id: position_id, round_id: @round_id}`. Rails' ActiveRecord defaults to `AND` of conditions when a hash is passed.

2017-06-06 14:59 UTC, freeatnet commented on app/services/chass_importer.rb
> +          )
Plus, we can reuse that hash here!

2017-06-06 15:02 UTC, freeatnet commented on app/services/chass_importer.rb
> +    @list = pref.split(',')
This probably shouldn't be an instance variable

2017-06-06 15:03 UTC, freeatnet commented on app/services/chass_importer.rb
> +    @preferences = @list.map do |pref|
Same here

2017-06-06 15:04 UTC, simpslandyy requested changes
Out of all the comments I've left, the one in the insert_application method is the most pressing. It should definitely be addressed before this gets pushed out. :)

2017-06-06 15:04 UTC, simpslandyy commented on db/seeds.rb
> +Campus.create!(code: 1, name: "St. George")
If the campus table is populated here, why not instantiate and use the JSON importer here as well?
Just a suggestion, cause it's a bit confusing why they are separated from each other

2017-06-06 15:04 UTC, simpslandyy commented on app/services/chass_importer.rb
> +          app_id: utorid,
app_id should be the app_id sent from CHASS.
applicant_id shouldn't exist, ids are generated for us when inserting records into the applicant table.

2017-06-06 15:04 UTC, simpslandyy commented on app/services/chass_importer.rb
> +    @course_data = JSON.parse(@data)["courses"]
You might want to add some error checking here, so we can detect a malformed json file.
Checking the existence of "courses" and "applicants" JSON should be good enough imo.

2017-06-06 15:04 UTC, freeatnet commented
Solid first contrib, mostly minor fixes to do!

2017-06-06 15:17 UTC, freeatnet commented on app/services/chass_importer.rb
> +          app_id: utorid,
@simpslandyy You're right. In fact, what we could do is look up Applicant first, then [utilize our associations](http://guides.rubyonrails.org/association_basics.html#has-many-association-reference) to check for existing Application or build a new one:
```
utorid = applicant_entry["utorid"]
applicant = Applicant.where(utorid: utorid).take! # find one or fail

check_duplicate = { app_id: applicant_entry["app_id"].to_i, round_id: @round_id }
condition = applicant.applications.exists?(check_duplicate)

application = applicant.applications.build({ # No need to set applicant_id manually anymore, it's taken in from the association
                                                                    app_id: applicant_entry["app_id"].to_i,
                                                                    round_id: @round_id,
                                                                    [… omitted …] })
```

2017-06-07 13:21 UTC, michellemtchai commented on app/services/chass_importer.rb
> +    return @course_data[0]["round_id"]
Okay. Good idea. I'll add this.

2017-06-07 13:22 UTC, michellemtchai commented on app/services/chass_importer.rb
> +          check_duplicate = ["applicant_id = ? and position_id = ? and round_id = ?",
Okay. I didn't know that. I'll add it.

2017-06-07 13:22 UTC, michellemtchai commented on app/services/chass_importer.rb
> +          )
How do I reuse the hash here?

2017-06-07 13:23 UTC, michellemtchai commented on app/services/chass_importer.rb
> +    @list = pref.split(',')
Not an instance variable? Does that mean that I should drop the @ in front of the list?

2017-06-07 13:31 UTC, michellemtchai commented on app/services/chass_importer.rb
> +    @preferences = @list.map do |pref|
Okay. I guess it really is the @ on the variable. I'll remove that.

2017-06-07 13:41 UTC, michellemtchai commented on app/services/chass_importer.rb
> +          app_id: utorid,
@simpslandyy Okay. I was confused about the `app_id` when I made the importer. I guess I didn't notice that `app_id` was in the sample JSON from CHASS. Thanks for catching this. :) 

@freeatnet I'll add your code.

2017-06-07 13:46 UTC, michellemtchai commented on db/seeds.rb
> +Campus.create!(code: 1, name: "St. George")
I guess I could move it to the importer. Though, I'm a bit concerned because the imported adds data to the active record every round, the campuses, on the other hand, doesn't need to be added each time. They are kind of fixed throughout the round. But, then again, it is weird to separate them... I guess I'll ask @freeatnet on whether to keep them separate or together on the same class.

2017-06-07 13:51 UTC, michellemtchai commented on app/services/chass_importer.rb
> +    @course_data = JSON.parse(@data)["courses"]
Would something like:
````
if @course_data != nil && @applicant_data!=nil
    @round_id = get_round_id
    insert_data
else
    put "Error: malformed JSON"
end
````

2017-06-07 14:07 UTC, freeatnet commented on app/services/chass_importer.rb
> +    @course_data = JSON.parse(@data)["courses"]
@michellemtchai Calling `Hash#fetch` instead of `Hash#[]` will cause an exception when key is not present. It's pretty descriptive, too. Check out https://github.com/uoft-tapp/tapp/commit/85085956c58b63812d9ab40e42b458b0fe6e26eb

2017-06-07 15:45 UTC, freeatnet commented on db/seeds.rb
> +Campus.create!(code: 1, name: "St. George")
I've moved the importer from the controller to a separate rake task, `db:seed:chass`. I was iffy on putting a call in `seeds.rb` directly, since the Campus data is required for the system, but mock CHASS data may not be desired.

You can import mock data using `docker-compose run rails-app db:seed:chass`.

We'll revisit a controller for this later.

2017-06-08 02:24 UTC, freeatnet approved these changes

2017-06-08 14:19 UTC, merged