Added GET /courses to view courses and position as JSON
uoft-tapp/old-orig-tapp pull request #32
Opened 2017-06-07 20:43 UTC by michellemtchai

- continuation of PR #31
- added GET /courses
- page should display an array of JSON with the following attributes:
  * course_id
  * course_name
  * semester
  * campus
  * instructor
  * positions
  * hr_positions
  * enrollment
  * qualifications
  * duties

2017-06-09 15:21 UTC, freeatnet commented on app/controllers/courses_controller.rb
> +      @courses = Course.where(condition).includes(:instructor, :positions)
Is there a case where the same code can return multiple courses?

2017-06-09 15:33 UTC, michellemtchai commented on app/controllers/courses_controller.rb
> +      @courses = Course.where(condition).includes(:instructor, :positions)
It can return multiple positions that is categorized under the course.

2017-06-09 16:33 UTC, simpslandyy reviewed
This looks great @michellemtchai, it just doesn't handle the cases where invalid course codes are passed in the query string (it returns an empty list). @freeatnet what will have to change so that this will trigger the handler in my PR?

2017-06-09 17:24 UTC, freeatnet commented on app/controllers/courses_controller.rb
> +      @courses = Course.where(condition).includes(:instructor, :positions)
That would still be under a single course record; let's use `Course.find(params[:code].upcase)` and move this into a `show` action, since it returns a single record.

2017-06-12 14:34 UTC, michellemtchai commented on app/controllers/courses_controller.rb
> +      @courses = Course.where(condition).includes(:instructor, :positions)
Since the `/courses/{code}/positions` routes was recently added, wouldn't it be better to move the `/courses?code={code}` to `/courses/{code}/positions`?

2017-06-13 13:37 UTC, freeatnet commented on app/controllers/courses_controller.rb
> +      @courses = Course.where(condition).includes(:instructor, :positions)
Semantically, `/courses/:code` should return a Course record at the top of the response, and `/courses/:code/positions` should return an array of positions.
Retrieval of a single course by code, whether with extra entities like positions or not, should still be under `/courses/:code` and handled by a `show` action.

2017-06-14 15:07 UTC, freeatnet commented on app/controllers/positions_controller.rb
> +    @course_positions = Position.where(condition)
We could use `Course.find(params[:course_code].upcase).positions` here.

2017-06-14 19:33 UTC, freeatnet commented on spec/controllers/positions_controller_spec.rb
> +    context "when {course_code} is an integer" do
This may be a little redundant: the `course_code` should specify a valid course code, and a previous test already verifies invalid `course_code` returns a 404. You don't need to remove it though.

2017-06-14 19:44 UTC, freeatnet requested changes
Awesome work, @michellemtchai! Loved the thorough testing of updates. There's one little quirk though: `PUT` or `PATCH` to `/courses/:code` and `/courses/:course_code/positions/:id` returns a `204 No Content` status on successful execution. Now, that's a perfectly valid status; however, it should probably be specifically tested and documented (just so we know to expect it).

2017-06-14 22:04 UTC, freeatnet approved these changes

2017-06-14 22:07 UTC, merged